### ISSUE TITLE
issue on querying data for hasMany through relation 

### ISSUE THREAD

**Issue by TonyLuo** [strongloop/loopback-connector-mysql#103] opened 2015-06-03 18:11 UTC
I test the hasmany through relation on mysql and mongodb using following version connector, it seems the connector cannot get the parameter from the scope :

loopback-connector-mysql version: 2.1.0
loopback-connector-mongodb:1.8.0

SysUser.json:
    "coms": {
      "type": "hasMany",
      "model": "SysCom",
      "foreignKey": "userId",
      "through": "SysEmp"

```
},
```

SysEmp.json:

"relations": {

```
"sysCom": {
  "type": "belongsTo",
  "model": "SysCom",
  "foreignKey": "comId"
},

"sysUser": {
  "type": "belongsTo",
  "model": "SysUser",
  "foreignKey": "userId"
},
```

query data using SysUser model:

include: [
    {
      relation: 'coms',
      scope: {
        where: {id: 'comA'}
      }
    }
  ]

debug info:
SQL: SELECT id,name,parentId FROM SysCom WHERE id IN (?) ORDER BY id, params: [null] +11ms

**Comment by TonyLuo** [comment] 2015-06-04 03:59
it works well on loopback-connector-mysql version: 1.7.0

**Comment by erikverheij** [comment] 2015-12-29 21:11
I've a similar problem; 

```
var filter = {
  where: { userId: userId},
  include: {
    relation: 'challenger',
    scope: {
      include: {
        relation: 'leagues',
        scope: {
          where: { id: 1 }
        }
      }
    }
  }
};
```

results in 

```
sql: 'SELECT `id`, `name` FROM `League` WHERE `id` IN (3,4,5,6) ORDER BY `id`'
```

In my case the ```WHERE `id`=1 ``` part is missing. I think this is because it has been overridden by the ``` WHERE `id` IN``` part which is required for the include relation.

**Comment by jannyHou** [comment] 2016-12-08 20:52
@TonyLuo If the problem is "scope filter" is applied on throughModel not relatedModel, I believe it's fixed in https://github.com/strongloop/loopback-datasource-juggler/pull/1153, the fix is on 3.x version but hasn't beed backported to 2.x(under discussion)

If that is not the case, can you fork https://github.com/strongloop/loopback-sandbox and replace with your use case? Thanks. I will try to reproduce it.

**Closed** 2016-12-09 00:59 UTC
Labels: triage, waiting
