### ISSUE TITLE
"npm test" failing

### ISSUE THREAD

**Issue by ghatwala** [strongloop/loopback-connector-mysql#130] opened 2015-10-27 06:34 UTC
Hi All,

When i try to run "npm test " , its failing with the below output . 
$ npm test
/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
        ^
AssertionError: expected {
[Error: ER_DBACCESS_DENIED_ERROR: Access denied for user ''@'localhost' to database 'myapp_test']
  code: 'ER_DBACCESS_DENIED_ERROR',
  errno: 1044,
  index: 0,
  sqlState: '42000'
} to not exist
    at /root/strongloop/loopback-connector-mysql/test/mysql.test.js:44:18
    at /root/strongloop/loopback-connector-mysql/node_modules/loopback-connector/node_modules/async/lib/async.js:52:16
    at done (/root/strongloop/loopback-connector-mysql/node_modules/loopback-connector/node_modules/async/lib/async.js:243:17)
    at /root/strongloop/loopback-connector-mysql/node_modules/loopback-connector/node_modules/async/lib/async.js:44:16
    at /root/strongloop/loopback-connector-mysql/node_modules/loopback-connector/lib/sql.js:1216:9
    at cbForWork (/root/strongloop/loopback-connector-mysql/node_modules/loopback-datasource-juggler/lib/observer.js:150:34)
    at /root/strongloop/loopback-connector-mysql/node_modules/loopback-connector/lib/sql.js:413:7
    at handleResponse (/root/strongloop/loopback-connector-mysql/lib/mysql.js:142:17)
    at Query._callback (/root/strongloop/loopback-connector-mysql/lib/mysql.js:180:13)
    at Query.Sequence.end (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
npm ERR! Test failed.  See above for more details.

Has anyone got the similar error as above , if yes , any pointers to resolve the above would be helpful .

**Comment by superkhau** [comment] 2015-10-27 21:07
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/481

**Comment by superkhau** [comment] 2015-10-27 21:07
I get the same error ATM. I believe @raymondfeng has a fix on a branch that needs merging.

**Comment by ghatwala** [comment] 2015-10-28 07:08
@superkhau , @raymondfeng  : Can you'll please let me know which branch do I need to check out for the above " npm test " to pass ?

**Comment by ghatwala** [comment] 2015-10-28 10:08
Hi @superkhau  @raymondfeng  : Just additional piece of information , I created a MySQL database , with that it's not giving me connectivity errors but some other errors , additional info :+1: 

[root@pts00449-vm19 loopback-connector-mysql]# npm test
TypeError: Cannot read property 'replace' of undefined
    at Object.SqlString.escapeId (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/SqlString.js:13:19)
    at /root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/SqlString.js:79:19
    at String.replace (native)
    at Object.SqlString.format (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/SqlString.js:71:14)
    at PoolConnection.Connection.format (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:274:20)
    at PoolConnection.query (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:196:22)
    at executeWithConnection (/root/strongloop/loopback-connector-mysql/lib/mysql.js:163:18)
    at Handshake.onConnect (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/Pool.js:59:7)
    at Handshake.Sequence.end (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.Sequence.OkPacket (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/root/strongloop/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:274:23)npm ERR! Test failed.  See above for more details.

**Comment by ghatwala** [comment] 2015-10-28 11:55
Hi ,

Additonal information on $ npm test

 119) Discover model primary keys should return an array of primary keys for STRONGLOOP.PRODUCT:
     Error: ER_DBACCESS_DENIED_ERROR: Access denied for user ''@'localhost' to database 'STRONGLOOP'
      at Handshake.Sequence._packetToError (node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
      at Handshake.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
      --------------------
      at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:135:48)
      at Protocol.handshake (node_modules/mysql/lib/protocol/Protocol.js:52:41)
      at PoolConnection.connect (node_modules/mysql/lib/Connection.js:123:18)
      at Pool.getConnection (node_modules/mysql/lib/Pool.js:45:23)
      at MySQL.executeSQL (lib/mysql.js:199:12)
      at node_modules/loopback-connector/lib/sql.js:408:10
      at node_modules/loopback-datasource-juggler/lib/observer.js:175:9
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at MySQL.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at MySQL.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at MySQL.ObserverMixin.notifyObserversAround (node_modules/loopback-datasource-juggler/lib/observer.js:144:15)
      at MySQL.SQLConnector.execute (node_modules/loopback-connector/lib/sql.js:407:8)
      at MySQL.discoverForeignKeys (lib/discovery.js:346:10)
      at DataSource.discoverForeignKeys (node_modules/loopback-datasource-juggler/lib/datasource.js:1060:20)
      at Context.<anonymous> (test/mysql.discover.test.js:177:8)

  120) Discover model foreign keys should return an array of foreign keys for STRONGLOOP.INVENTORY:
     Error: ER_DBACCESS_DENIED_ERROR: Access denied for user ''@'localhost' to database 'STRONGLOOP'
      at Handshake.Sequence._packetToError (node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
      at Handshake.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
      --------------------
      at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:135:48)
      at Protocol.handshake (node_modules/mysql/lib/protocol/Protocol.js:52:41)
      at PoolConnection.connect (node_modules/mysql/lib/Connection.js:123:18)
      at Pool.getConnection (node_modules/mysql/lib/Pool.js:45:23)
      at MySQL.executeSQL (lib/mysql.js:199:12)
      at node_modules/loopback-connector/lib/sql.js:408:10
      at node_modules/loopback-datasource-juggler/lib/observer.js:175:9
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at MySQL.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at MySQL.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at MySQL.ObserverMixin.notifyObserversAround (node_modules/loopback-datasource-juggler/lib/observer.js:144:15)
      at MySQL.SQLConnector.execute (node_modules/loopback-connector/lib/sql.js:407:8)
      at MySQL.discoverPrimaryKeys (lib/discovery.js:298:10)
      at DataSource.discoverPrimaryKeys (node_modules/loopback-datasource-juggler/lib/datasource.js:1004:20)
      at Context.<anonymous> (test/mysql.discover.test.js:160:8)

  121) Discover LDL schema from a table should return an LDL schema for INVENTORY:
     Error: ER_DBACCESS_DENIED_ERROR: Access denied for user ''@'localhost' to database 'STRONGLOOP'
      at Handshake.Sequence._packetToError (node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
      at Handshake.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
      --------------------
      at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:135:48)
      at Protocol.handshake (node_modules/mysql/lib/protocol/Protocol.js:52:41)
      at PoolConnection.connect (node_modules/mysql/lib/Connection.js:123:18)
      at Pool.getConnection (node_modules/mysql/lib/Pool.js:45:23)
      at MySQL.executeSQL (lib/mysql.js:199:12)
      at node_modules/loopback-connector/lib/sql.js:408:10
      at node_modules/loopback-datasource-juggler/lib/observer.js:175:9
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at MySQL.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at MySQL.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at MySQL.ObserverMixin.notifyObserversAround (node_modules/loopback-datasource-juggler/lib/observer.js:144:15)
      at MySQL.SQLConnector.execute (node_modules/loopback-connector/lib/sql.js:407:8)
      at MySQL.discoverForeignKeys (lib/discovery.js:346:10)
      at DataSource.discoverForeignKeys (node_modules/loopback-datasource-juggler/lib/datasource.js:1060:20)
      at Context.<anonymous> (test/mysql.discover.test.js:191:8)

  122) Discover and build models should discover and build models:
     Uncaught TypeError: Cannot read property 'name' of undefined
      at test/mysql.discover.test.js:210:20
      at node_modules/loopback-datasource-juggler/lib/datasource.js:1229:13
      at node_modules/loopback-datasource-juggler/lib/datasource.js:1302:7
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
      at done (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:161:15)
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:393:21
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:728:34
      at callback (lib/discovery.js:241:9)
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:150:34)
      at node_modules/loopback-connector/lib/sql.js:413:7
      at executeWithConnection (lib/mysql.js:159:26)
      at Handshake.onConnect (node_modules/mysql/lib/Pool.js:54:9)
      at Handshake.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Handshake.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  123) mysql "before all" hook:
     Uncaught TypeError: Cannot read property 'Inventory' of undefined
      at test/mysql.discover.test.js:233:20
      at node_modules/loopback-datasource-juggler/lib/datasource.js:1598:13
      at node_modules/loopback-datasource-juggler/lib/datasource.js:1302:7
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
      at done (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:161:15)
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:393:21
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:728:34
      at callback (lib/discovery.js:241:9)
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:150:34)
      at node_modules/loopback-connector/lib/sql.js:413:7
      at executeWithConnection (lib/mysql.js:159:26)
      at Handshake.onConnect (node_modules/mysql/lib/Pool.js:54:9)
      at Handshake.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Handshake.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  124) mysql "after all" hook:
     Uncaught TypeError: Cannot read property 'replace' of undefined
      at Object.SqlString.escapeId (node_modules/mysql/lib/protocol/SqlString.js:13:19)
      at node_modules/mysql/lib/protocol/SqlString.js:79:19
      at String.replace (native)
      at Object.SqlString.format (node_modules/mysql/lib/protocol/SqlString.js:71:14)
      at PoolConnection.Connection.format (node_modules/mysql/lib/Connection.js:274:20)
      at PoolConnection.query (node_modules/mysql/lib/Connection.js:196:22)
      at executeWithConnection (lib/mysql.js:163:18)
      at Handshake.onConnect (node_modules/mysql/lib/Pool.js:59:7)
      at Handshake.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Handshake.Sequence.OkPacket (node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  125) Persistence hooks "before each" hook: setupDatabase:
     Uncaught TypeError: Cannot read property 'replace' of undefined
      at Object.SqlString.escapeId (node_modules/mysql/lib/protocol/SqlString.js:13:19)
      at node_modules/mysql/lib/protocol/SqlString.js:79:19
      at String.replace (native)
      at Object.SqlString.format (node_modules/mysql/lib/protocol/SqlString.js:71:14)
      at PoolConnection.Connection.format (node_modules/mysql/lib/Connection.js:274:20)
      at PoolConnection.query (node_modules/mysql/lib/Connection.js:196:22)
      at executeWithConnection (lib/mysql.js:163:18)
      at Handshake.onConnect (node_modules/mysql/lib/Pool.js:59:7)
      at Handshake.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Handshake.Sequence.OkPacket (node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  126) transactions with promise "before all" hook:
     Uncaught TypeError: Cannot read property 'replace' of undefined
      at Object.SqlString.escapeId (node_modules/mysql/lib/protocol/SqlString.js:13:19)
      at node_modules/mysql/lib/protocol/SqlString.js:79:19
      at String.replace (native)
      at Object.SqlString.format (node_modules/mysql/lib/protocol/SqlString.js:71:14)
      at PoolConnection.Connection.format (node_modules/mysql/lib/Connection.js:274:20)
      at PoolConnection.query (node_modules/mysql/lib/Connection.js:196:22)
      at executeWithConnection (lib/mysql.js:163:18)
      at Handshake.onConnect (node_modules/mysql/lib/Pool.js:59:7)
      at Handshake.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Handshake.Sequence.OkPacket (node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  127) transactions "before all" hook:
     Uncaught TypeError: Cannot read property 'replace' of undefined
      at Object.SqlString.escapeId (node_modules/mysql/lib/protocol/SqlString.js:13:19)
      at node_modules/mysql/lib/protocol/SqlString.js:79:19
      at String.replace (native)
      at Object.SqlString.format (node_modules/mysql/lib/protocol/SqlString.js:71:14)
      at PoolConnection.Connection.format (node_modules/mysql/lib/Connection.js:274:20)
      at PoolConnection.query (node_modules/mysql/lib/Connection.js:196:22)
      at executeWithConnection (lib/mysql.js:163:18)
      at Handshake.onConnect (node_modules/mysql/lib/Pool.js:59:7)
      at Handshake.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Handshake.Sequence.OkPacket (node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

**Comment by ghatwala** [comment] 2015-10-30 07:36
hi @superkhau , @raymondfeng  ,

As per above " I get the same error ATM. I believe @raymondfeng has a fix on a branch that needs merging." 

Please let me know if you have merged ur changes to resolve the above mentioned test cases failures on rhel .... Any pointers on how to resolve the above test case failures will be helpful.

**Comment by raymondfeng** [comment] 2015-11-24 18:11
1. Please use the following script to set up `STRNGLOOP` database
https://github.com/strongloop/loopback-connector-mysql/blob/master/example/table.sql

2. Make sure the `test` user has all permissions to the DBs.

**Comment by cgole** [comment] 2015-11-24 18:13
@ghatwala, for the db setup you need to run this script https://github.com/strongloop/loopback-connector-mysql/blob/master/example/table.sql. Make sure you have the right permissions on the db. You can also set the TEST_* env variables, used in this script to force the tests to connect to your db server https://github.com/strongloop/loopback-connector-mysql/blob/master/test/init.js

**Comment by ghatwala** [comment] 2015-11-25 12:33
@cgole , @raymondfeng  -  i have set up STRONGLOOP database and granted permission to user 'amit' to access it. Please see the database/tables below to verify if the database is correctly configured.

/********/
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| STRONGLOOP         |
| strongloop         |
| test               |
+--------------------+
4 rows in set (0.00 sec)

mysql> show tables;
+----------------------+
| Tables_in_STRONGLOOP |
+----------------------+
| DateData             |
| NestedAddress        |
| NumberData           |
| PostTX               |
| PostWithDefaultId    |
| PostWithStringId     |
| PostWithUniqueTitle  |
| ReviewTX             |
| StringData           |
| TestModel            |
| UserData             |
| UserWithAddress      |
| customer_test        |
+----------------------+
13 rows in set (0.00 sec)
/*********/

I even edited the test/init.js file to add my configurations manually.
/***************/
 var dbConf = {
    host: '127.0.0.1',
    port: 3306,
    database: 'STRONGLOOP',
    username: 'amit',
    password: 'amit',
    createDatabase: true
     };
/***************/

However , even after doing above , when i run command for test cases as below  , i have 7 test failures -
#npm test
I have below results - 
/**************/

738 passing (28s)
  23 pending
  7 failing
Please see the attached file for logged errors. 

[debug.txt](https://github.com/strongloop/loopback-connector-mysql/files/43810/debug.txt)

Any pointers in this would be helpful.

**Comment by meghalidhoble** [comment] 2015-12-02 12:03
In continuation with the above configurations done by Amit, I am looking into the test-case failures. 
The one I am looking into is as below:
 1) MySQL specific datatypes should fail spectacularly with invalid enum values:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at test/datatypes.test.js:44:14
      at createCallback (node_modules/loopback-datasource-juggler/lib/dao.js:285:20)
      at node_modules/loopback-connector/lib/sql.js:431:7
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:150:34)
      at node_modules/loopback-connector/lib/sql.js:413:7
      at handleResponse (lib/mysql.js:142:17)
      at Query._callback (lib/mysql.js:153:7)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:274:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:96:28)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

After debugging file "test/datatypes.test.js", I found that the test-case looks correct; however the code is getting below error:

{ [Error: WARN_DATA_TRUNCATED: Data truncated for column 'animal' at row 1]
  code: 'WARN_DATA_TRUNCATED',
  errno: 1265,
  sqlState: '01000',
  index: 0 }

The test case is for invalid-enum validation. I am still looking to root-cause it, however any pointers in case someone has already seen this issue would help.
Thanks,
Meghali

**Comment by bajtos** [comment] 2015-12-03 17:15
We agreed with @superkhau to timebox the work on this issue to 5 story points in this sprint (85).

**Comment by superkhau** [comment] 2015-12-04 20:04
### Status update

I am able to reproduce the case outlined by @meghalidhoble. Seeing what I can do to fix it ATM.

**Comment by superkhau** [comment] 2015-12-05 00:35
@raymondfeng The datatype test is failing and I think it's supposed to, but please confirm these lines: https://github.com/strongloop/loopback-connector-mysql/blob/master/test/datatypes.test.js#L42-L48

You are put `assert(!err)` but MySQL is returning the data truncating value because you're trying to insert 'horse', which is not a valid enum value in this case (and therefore giving us the correct error). I believe the test should be:

```
assert(err); // should pass when there is an error because we do expect MySQL to fail spectacularly
```

If this is the case, I will send the fix in a PR.

/cc @ghatwala @meghalidhoble

**Comment by superkhau** [comment] 2015-12-08 23:11
Fixes are being work on at https://github.com/strongloop/loopback-connector-mysql/pull/140

**Comment by superkhau** [comment] 2015-12-08 23:32
#### Status update

This is related to the second failing test/blocker.

@bajtos The strict issue I was talking about is here: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2460. Basically, if you turn on strict mode, and pass in only invalid values (ie. `{foo: 'bar'}`) like the unit test does, you end up with an empty object `{}` because it gets stripped out later on. This means you end up with an invalid query that looks like `UPDATE QUERY SET WHERE id=?`.

Anyways, the fix isn't so simple because If I simply create an error and pass it to the callback, 20 something other tests fail. I've already spent the 5 points we timeboxed for this issue anyway, so we can discuss this further and attack it again during sprint planning.

**Comment by bajtos** [comment] 2015-12-09 15:20
@superkhau please always add commit sha to the URL by pressing `y` inside the page. Otherwise the the link may get outdated in the future. Here is the correct link for posterity: https://github.com/strongloop/loopback-datasource-juggler/blob/80c3bd9d419e501d5b7beb0a623c8b1eaefdc258/lib/dao.js#L2460

**Comment by bajtos** [comment] 2015-12-09 15:21
> @superkhau Basically, if you turn on strict mode, and pass in only invalid values (ie. `{foo: 'bar'}`) like the unit test does, you end up with an empty object `{}` because it gets stripped out later on. This means you end up with an invalid query that looks like `UPDATE QUERY SET WHERE id=?`.

I did a bit of code archaeology and found that this behaviour was introduced recently (July this year) via https://github.com/strongloop/loopback-datasource-juggler/pull/666 with the intention to fix https://github.com/strongloop/loopback/issues/742.

@fabien @raymondfeng what's your opinion on this? How should the MySQL connector handle this particular edge case?

**Comment by bajtos** [comment] 2015-12-10 15:14
@superkhau I am little bit confused by the label combo `blocked + triage + #wip`, is it still accurate?

**Comment by superkhau** [comment] 2015-12-10 17:24
Removing triage label as I've dug into it enough to know what we need to do.

**Comment by superkhau** [comment] 2015-12-10 17:42
>@superkhau please always add commit sha to the URL by pressing y inside the page. Otherwise the the link may get outdated in the future. Here is the correct link for posterity: https://github.com/strongloop/loopback-datasource-juggler/blob/80c3bd9d419e501d5b7beb0a623c8b1eaefdc258/lib/dao.js#L2460

Nice, didn't know about this feature. Will do!

**Comment by superkhau** [comment] 2015-12-14 01:02
As per @chandadharap, @raymondfeng should be available to fix things that are broken in CI. I can take it on, but it'll obviously take me longer than him.

@raymondfeng I can fix this just might take me longer than you, please advise on what to do going forward. Either you can fix it so we can have CI passing or perhaps you can advise me on the decisions that need to be made for items with long term implications. ie) the question from above:

>@fabien @raymondfeng what's your opinion on this? How should the MySQL connector handle this particular edge case?

**Comment by raymondfeng** [comment] 2015-12-14 16:43
@superkhau You can add a check at https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L623 to see if the `data` object is empty. If yes, call back with cb(null, {count: 0}).

**Comment by superkhau** [comment] 2015-12-15 03:41
>@superkhau You can add a check at https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L623 to see if the data object is empty. If yes, call back with cb(null, {count: 0}).

Turns out this isn't the issue. I ran that test independently and it passes on its own now. I'm pretty much considering this a lost cause. I can't consistently run the testing environment because I get different results each time I run the tests. There are obviously race conditions or something messing up the test results. Do you want to take a stab at fixing this @raymondfeng? I'm pretty much blocked.

**Comment by superkhau** [comment] 2015-12-15 06:07
@raymondfeng Now master is all green without any of my commits LOL. There are obviously issues. http://ci.strongloop.com/job/loopback-connector-mysql/. IMO, we gotta do something about these long tests and race conditions, shared test envs, bastardization of e2e tests: http://googletesting.blogspot.ca/2015/04/just-say-no-to-more-end-to-end-tests.html

Closing this issue as resolved.

**Closed** 2015-12-15 06:08 UTC
Labels: #review, bug
