### ISSUE TITLE
Array of objects are saved as [Object Object]

### ISSUE THREAD

**Issue by zmarouf** [strongloop/loopback-connector-mysql#65] opened 2015-01-02 14:29 UTC
Hello!

I've been playing with loopback for a few days and I'm having trouble with a specific field in my model:

```
 "myField": {
   "type": [
     "object"
   ],
   "required": false
 }
```

If I try to set it like so:

```
...
myModel.myField = [{'atr1': "value1", 'atr2': "value2"}];
...
MyModel.upsert(myModel, function (err) {
  if (err) console.log(err);
});
```

I get something weird in the resulting row field:

```
+-----------------+                         +----------------------------------------+
| myField         |                         | myField                                |
+-----------------+        instead of       +----------------------------------------+
| [object Object] |                         | [{"atr1":"value1","atr2":"value2"}]    |
+-----------------+                         +----------------------------------------+

```

Could someone enlighten me as to what I'm doing wrong?

**Comment by zmarouf** [comment] 2015-01-02 16:35
Further tests show that it happens with the way I use upsert or updateAttributes. I changed my code to use the static updateAll and it works now. 

I still don't understand why what I was doing is wrong though, so if anyone has an explanation for me, I'm all ears :)

**Comment by smehrbrodt** [comment] 2015-04-08 08:40
I think this is fixed with 634a0a94bcba033bc7748b97a7f7921f54d1e1e4

**Comment by johannesjo** [comment] 2016-02-19 01:13
This happens to me also with the standard create method.

**Comment by b-admike** [comment] 2017-03-31 19:47
@zmarouf I have tried your scenario with `upsertWithWhere` and was able to successfully get the following:
Steps to reproduce:
1) create a LB 2.x app with `empty-server` template
2) create a mysql datasource using the generator prompt `slc loopback:datasource`
3) use `slc loopback:model` to create `myModel`
4) make `create-mymodel.js` which calls automigrate function on `myModel`
5) start app and in explorer do a POST request to `myModels` with following value:
```
{   "myField": [     {"atr1": "value1",      "atr2": "value2"     }   ] }
```
6) Check database
```
mysql> select * from myModel;
+----+-------------------------------------+
| id | myField                             |
+----+-------------------------------------+
|  1 | [{"atr1":"value1","atr2":"value2"}] |
+----+-------------------------------------+
1 row in set (0.00 sec)

```
6) do a POST request to `UpsertWithWhere` endpoint and specify the following:
```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"myField\": [
    {\"atr1\": \"value3\",
     \"atr2\": \"value4\"
    }
  ]
}" "http://localhost:3000/api/myModels/upsertWithWhere?where=%7B%20%20%20%22myField%22%3A%20%5B%20%20%20%20%20%7B%22atr1%22%3A%20%22value1%22%2C%20%20%20%20%20%20%22atr2%22%3A%20%22value2%22%20%20%20%20%20%7D%20%20%20%5D%20%7D"
```
7. check database again
```
mysql> select * from myModel;
+----+-------------------------------------+
| id | myField                             |
+----+-------------------------------------+
|  1 | [{"atr1":"value3","atr2":"value4"}] |
+----+-------------------------------------+
1 row in set (0.01 sec)
```

I have created a sample repo which has the app that can verify the issue is fixed [sample repo](https://github.com/b-admike/mysql65)

**Closed** 2017-03-31 19:48 UTC
Labels: triaging
