### ISSUE TITLE
Multi Column Index Throwing 500 error on duplicate creation

### ISSUE THREAD

**Issue by kodepareek** [strongloop/loopback-connector-mysql#263] opened 2017-04-20 07:22 UTC
Hi guys

I am on LB 3. 

I have `team` and `appUser` models which are linked by `hasManyThrough` via a `teamappUser` model. 

I created a unique together constraint on `teamId` and `appUserId` on in the `teamappUser` 

On testing for duplicate key creation (testing if unique together constraint was successful ) I get a 500 internal server error and server restart. 

I feel a 500 is completely unwarranted for what is expected behaviour on part of the app. This should be a 4XX error and should not cause the server to crash. 

package version 4.0.0

The Models are all very basic. 

Output on console. 

```
loopback:connector:mysql SQL: SELECT `id`,`ttl`,`created`,`userId`,`appUserId` FROM `AccessToken` WHERE `id`=? ORDER BY `id` LIMIT 1, params: ["l8vY592xJjF6SxrEawMvUPCzWNqZAZpwZNaccpgoANIdzzSmquAKaRFDLwPLrCDr"] +0ms
  loopback:connector:mysql Data:  +7ms [ RowDataPacket {
    id: 'l8vY592xJjF6SxrEawMvUPCzWNqZAZpwZNaccpgoANIdzzSmquAKaRFDLwPLrCDr',
    ttl: 1209600,
    created: 2017-04-19T07:33:07.000Z,
    userId: 1,
    appUserId: null } ]
  loopback:connector:mysql SQL: INSERT INTO `teamappUser`(`teamId`,`appUserId`) VALUES(?,?), params: [2,2] +50ms
  loopback:connector:mysql Error: {"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","index":0} +59ms
  loopback:connector:mysql Data:  +0ms undefined
Unhandled error for request POST /api/teamappUsers?access_token=l8vY592xJjF6SxrEawMvUPCzWNqZAZpwZNaccpgoANIdzzSmquAKaRFDLwPLrCDr: Error: ER_DUP_ENTRY: Duplicate entry '2-2' for key 'teamIdAppUserId'



```

**Comment by kjdelisle** [comment] 2017-05-29 18:20
@kodepareek Sorry about the super late reply, we're churning through quite a large backlog here!

Do you have an example repository that we can use to reproduce? I can try to recreate the problem myself, but having an example that you know demonstrates the issue would definitely speed this up.

**Comment by kjdelisle** [comment] 2017-05-29 20:20
@kodepareek An update:

I've recreated the scenario above, but I can't reproduce a failure of the application itself.
```
Unhandled error for request POST /api/TeamAppUsers: Error: ER_DUP_ENTRY: Duplicate entry '1-1' for key 'team_app_user'
    at Query.Sequence._packetToError (/home/bitwise/sandbox/duplicate-create-throws-500/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/bitwise/sandbox/duplicate-create-throws-500/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/bitwise/sandbox/duplicate-create-throws-500/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/bitwise/sandbox/duplicate-create-throws-500/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/bitwise/sandbox/duplicate-create-throws-500/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/bitwise/sandbox/duplicate-create-throws-500/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```
I still receive the 500 Internal Server Error, but the application continues on as normal (subsequent requests to the API succeed).

I do agree that this should be returning `422 Unprocessable Entity`, since the request is syntactically valid, it's just semantically incorrect.

**Comment by kodepareek** [comment] 2017-05-30 07:43
Sorry this has been a while and my code has changed completely in the meantime. Will take a lot of looking to find where things are. 

I might have mistaken a 500 for a server restart. Would be my bad in that case.

**Comment by kjdelisle** [comment] 2017-05-31 21:09
Fix merged and should be out in 2.x! Thanks for the report and, again, sorry it took so long to get to this. Your help is greatly appreciated!

**Closed by kjdelisle** 2017-05-31 21:09 UTC
Labels: apex, bug, review
