### ISSUE TITLE
Indexes do not work as per documentation

### ISSUE THREAD

**Issue by wrensburg** [strongloop/loopback-connector-mysql#109] opened 2015-07-13 17:40 UTC
Following the documentation here: http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Indexes, the following items about indexes do not work:

- `options.unique` is not honored at the composite index definition
- `<indexName>.keys` is not honored and fails when running auto migration
- No documentation about the use of `columns`
- Composite indexes with sort order do not work

**Comment by saystone** [comment] 2015-07-14 05:12
:+1:

**Comment by DylanSale** [comment] 2016-04-27 01:01
Just encountered this. 

Had to use :

``` json
"indexes" : {
    "unique_conversationInstance_member_index": {
      "columns": "memberId, conversationInstanceId",
      "kind": "unique"
    }
  }
```

instead of what I would expect from the documentation:

``` json
"indexes" : {
    "unique_conversationInstance_member_index": {
      "keys": {
          "memberId": 1,
          "conversationInstanceId": 1
      },
      "options": { 
           "unique": true
      }
    }
  }
```

**Comment by superkhau** [comment] 2016-04-27 01:47
@crandmck ^

**Comment by raymondfeng** [comment] 2016-04-27 23:10
We need to fix the connector to conform to what's documented.

**Comment by crandmck** [comment] 2016-04-27 23:11
OK, so @superkhau that means this is not a doc issue, and we should open issues against the connectors that don't yet conform... right?

**Comment by superkhau** [comment] 2016-04-27 23:23
@crandmck Yes, now they are bug fixes instead. ;)

**Comment by deepakrkris** [comment] 2016-07-26 17:54
from an initial code analysis the issue is in /lib/migration.js :  MySQL.prototype.buildIndexes() , 

for the create table functionality, 

1. An array type check is made for the keys field,  whereas keys is an object field.
           `if (Array.isArray(i.keys)) {`
2. Configuration for unique index is taken from the "kind" attribute, and so the options.unique=true configuration is ignored.
           `if (i.kind) {
                kind = i.kind;
            }`
There seems to be other inconsistencies in general when compared to other connectors. So I am going to take a closer look before fixing only for the above.

**Comment by deepakrkris** [comment] 2016-07-28 13:46
I see that the configuration fields "kind" and "columns" are now added in the documentation.
https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-MySQLindexes
Should we remove those fields are continue to keep them ?

**Comment by deepakrkris** [comment] 2016-07-29 16:29
Index sorting is not supported in MySQL. http://dev.mysql.com/doc/refman/5.5/en/create-index.html : 

> An index_col_name specification can end with ASC or DESC. These keywords are permitted for future extensions for specifying ascending or descending index value storage. Currently, they are parsed but ignored; index values are always stored in ascending order.

so the 4th issue reported cannot be fixed in the connector

**Closed** 2016-08-15 17:09 UTC
Labels: bug
