### ISSUE TITLE
autoupdate() fails when adding new required date field with defaultFn: now

### ISSUE THREAD

**Issue by henkosch** [strongloop/loopback-connector-mysql#315] opened 2017-07-28 12:39 UTC
# Description/Steps to reproduce

I have extended a custom loopback model with a new required property with type date (defaultFn: "now").

``` 
    ...
    "date": {
      "type": "date",
      "required": true,
      "defaultFn": "now"
    }
    ...
```

Then I used autoupdate() to extend the mysql table schema with the new field, but the table had some existing data in it, which it could not handle properly.

The autoupdate failed with the following error:
`Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '0000-00-00 00:00:00' for column 'date' at row 1`

# Expected result

I was expecting it to create a new date field in the table and update existing rows to have the current date in the date field as it is the default value.

# Additional information

See also: https://github.com/strongloop/loopback-datasource-juggler/pull/458

**Comment by ssh24** [comment] 2017-07-29 21:51
@henkosch Sorry, I was not able to follow your reproduction steps correctly to reproduce this issue. From my understanding, you had some existing data on your database and then you decided to add a new field **date** which has the property `"defaultFn": "now"` set to it. If that is correct, then I was not able to reproduce your issue.

Here is sample scripts that breaks down the reproduction step:

1. Original model definition

```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

2. Boot script to seed some data

```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.mysqlDs;
    var Employee = app.models.Employee;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Employee.create([{
            name: 'Foo'
        }, {
            name: 'Bar'
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));
        });
    });
};
```

3. Database output after steps 1 and 2

```bash
mysql> select * from Employee;
+----+------+
| id | name |
+----+------+
|  1 | Foo  |
|  2 | Bar  |
+----+------+
2 rows in set (0.00 sec)

mysql> describe Employee;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | int(11)      | NO   | PRI | NULL    | auto_increment |
| name  | varchar(512) | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
2 rows in set (0.00 sec)
```

4. Change the model definition to add `"defaultFn": "now"` to **date** field

```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "date": {
      "type": "date",
      "defaultFn": "now"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

5. Boot script to perform autoupdate

```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.mysqlDs;
    var Employee = app.models.Employee;

    db.autoupdate(function(err) {
        if (err) throw err;
        console.log('\nAutoupdate completed');

        Employee.create([{
            name: 'Foo-new'
        }, {
            name: 'Bar-new'
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));
        });
    });
};
```

6. Database output after step 4 and 5

```bash
mysql> describe Employee;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | int(11)      | NO   | PRI | NULL    | auto_increment |
| name  | varchar(512) | YES  |     | NULL    |                |
| date  | datetime     | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
3 rows in set (0.00 sec)

mysql> select * from Employee;
+----+---------+---------------------+
| id | name    | date                |
+----+---------+---------------------+
|  1 | Foo     | NULL                |
|  2 | Bar     | NULL                |
|  3 | Foo-new | 2017-07-29 21:44:09 |
|  4 | Bar-new | 2017-07-29 21:44:09 |
+----+---------+---------------------+
4 rows in set (0.00 sec)
```

Please let me know what steps were different on your reproduction so I can debug more on the issue.

**Comment by henkosch** [comment] 2017-08-01 03:01
Hello,

Thank you for your detailed steps for reproduction. However you are missing one key element. 

I also added the **required: true** flag to the newly added date field, so it cannot be NULL in the database. This needs the field to have a default value in the schema definition which should be set to the current date.

So step 4. should be:

```
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "date": {
      "type": "date",
      "defaultFn": "now",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

Please note that there cannot be NULL values in the date field after autoupdate.

**Comment by ssh24** [comment] 2017-08-04 11:05
I can confirm this is a bug. Adding to the backlog.

**Comment by ssh24** [comment] 2017-08-23 15:44
@henkosch After a lot of digging and a [recent PR](https://github.com/strongloop/loopback-connector-mysql/pull/319) to allow default values in MySQL that persists the default value in the database, I figured out it is not a bug.

The way the **required** flag works in LoopBack, it enforces on creation of an instance, the property to be specified. Hence, if you specify both **a default value** for a property and make it **required** it is complementing each other (because if you skip that property, it will throw a validation error!).

Here is a sample reproduction:

1. Original model definition

```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

2. Boot script to seed some data

```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.mysqlDs;
    var Employee = app.models.Employee;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Employee.create([{
            name: 'Foo'
        }, {
            name: 'Bar'
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));
        });
    });
};
```

3. Database output after steps 1 and 2

```bash
mysql> select * from Employee;
+----+------+
| id | name |
+----+------+
|  1 | Foo  |
|  2 | Bar  |
+----+------+
2 rows in set (0.00 sec)

mysql> describe Employee;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | int(11)      | NO   | PRI | NULL    | auto_increment |
| name  | varchar(512) | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
2 rows in set (0.00 sec)
```

4. Update the model definition with a new field **date**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }, 
    "date": {
      "type": "date",
      "mysql": {
        "default": "now"
      }
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

5. Boot script to perform autoupdate
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.mysqlDs;
    var Employee = app.models.Employee;

    db.autoupdate(function(err) {
        if (err) throw err;
        console.log('\nAutoupdate completed');

        Employee.create([{
            name: 'Foo-new'
        }, {
            name: 'Bar-new'
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));
        });
    });
};
```

6. Database output after steps 4 and 5
```bash
mysql> describe Employee;
+-------+--------------+------+-----+-------------------+----------------+
| Field | Type         | Null | Key | Default           | Extra          |
+-------+--------------+------+-----+-------------------+----------------+
| id    | int(11)      | NO   | PRI | NULL              | auto_increment |
| name  | varchar(512) | YES  |     | NULL              |                |
| date  | datetime     | YES  |     | CURRENT_TIMESTAMP |                |
+-------+--------------+------+-----+-------------------+----------------+
3 rows in set (0.00 sec)

mysql> select * from Employee;
+----+---------+---------------------+
| id | name    | date                |
+----+---------+---------------------+
|  1 | Foo     | 2017-08-23 15:34:19 |
|  2 | Bar     | 2017-08-23 15:34:19 |
|  3 | Foo-new | 2017-08-23 15:34:19 |
|  4 | Bar-new | 2017-08-23 15:34:19 |
+----+---------+---------------------+
4 rows in set (0.00 sec)
```

Closing this issue as resolved. Feel free to reopen if needed.

**Closed by ssh24** 2017-08-23 15:44 UTC
Labels: bug, committed, team-apex
