### ISSUE TITLE
MySQL migration hang with a new empty application if there are two datasources using MySQL

### ISSUE THREAD

**Issue by Mayeu** [strongloop/loopback-connector-mysql#264] opened 2017-04-21 13:25 UTC
# Description/Steps to reproduce

For the last 3 months we had a LoopBack application using a MySQL and a REST datasource. Recently we wanted to add a new datasource pointing to another MySQL database. This datasource don't have any migration because we are calling an existing database managed by another application.

While the application is still working (we can launch the server, and use the whole shebang with the second database), the database migration of the first MySQL database are now hanging indefinitively (unless killed, or killing the database).

1. Create a new empty Loopback API server (v3)
2. Add one datasource using mysql
3. Create a simple migration script:
```javascript
var server = require('./server');

/* Initialise MySQL database */

var mysql_db = server.dataSources.dbone;
var lbTables = ['User', 'ACL', 'RoleMapping', 'Role'];

mysql_db.autoupdate(lbTables, function(er) {
    if (er) {
        throw er;
    }
    console.log('Loopback tables [' + lbTables + '] created in ', mysql_db.adapter.name);
    mysql_db.disconnect();
});
```
4. Run the migration script successfully
5. Add a new datasource
6. Try to run the same migration script, which will now hang indefinitively.

I have created a minimal non working example of this at [Mayeu/loopback-two-mysql-datasource-not-working](https://github.com/Mayeu/loopback-two-mysql-datasource-not-working):
* It's the default empty application, with two MySQL datasource in it
* The mysql migration script try to create the default models (Users, ACL, etc.)
* The demo uses docker for the database, yarn, and nvm so you have the exact dependency tree of the application.

You can run the whole things with the `./demo.sh` script in it, the result will be something like:
```
$ nvm use
$ ./demo.sh
==> Create two containers for MySQL, and start those
35b97671989a98246786e42b8a10b9615ef00a9cd4e48829dfb2ae5ec6c3cc0f
050a244b11b14321eac5aabf50e42159f8d0066f3560ee466e3fdb85b1859125
mysql-dbone
mysql-dbtwo
==> Wait 20 seconds, to ensure the MySQL are started
==> Export the needed MySQL definition string
==> Install the needed package
yarn install v0.23.2
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.49s.
==> Checkout the working code with only one datasource
Note: checking out '4b7aa8c528e9fa4f42a4663613d137a4f95bb8c5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4b7aa8c... Minimal working example
==> Run the migration script
Loopback tables [User,ACL,RoleMapping,Role] created in  mysql
==> The migration finished
==> Checkout the non working code with two MySQL's datasources
Previous HEAD position was 4b7aa8c... Minimal working example
HEAD is now at f221371... Add one datasource with mysql, migration breaks
==> Run the migration script
Loopback tables [User,ACL,RoleMapping,Role] created in  mysql
## Hang indefinitively here
```
# Expected result

The migration finish correctly.

# Additional information
```
🚀  λ node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 6.10.2

🚀  λ npm ls --prod --depth 0 | grep loopback
loopback-test@1.0.0 /Users/cast/Code/loopback-test
├── loopback@3.6.0
├── loopback-boot@2.24.0
├── loopback-component-explorer@4.2.0
├── loopback-connector-mysql@4.0.0
npm ERR! missing: options@latest, required by sse@0.0.6
```

### Thanks in advance for any help :)

**Comment by ssh24** [comment] 2017-05-01 23:23
@Mayeu I was not successful on reproducing your issue. I have created my own sample script and app, and it works as expected. 

This my `datasources.json` file:
```json
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "mysqlDS1": {
    "host": "0.0.0.0",
    "port": 3307,
    "url": "",
    "database": "sample",
    "password": "****",
    "name": "mysqlDS1",
    "user": "root",
    "connector": "mysql"
  },
    "mysqlDS2": {
    "host": "0.0.0.0",
    "port": 3308,
    "url": "",
    "database": "sample",
    "password": "****",
    "name": "mysqlDS2",
    "user": "root",
    "connector": "mysql"
  }
}
```

Here is my script:
```javascript
'use strict';
var async = require('async');

module.exports = function(app) {
  var mysqlDB = app.dataSources.mysqlDS1;
  var lbTables = ['User', 'ACL', 'RoleMapping', 'Role'];

  mysqlDB.autoupdate(lbTables, function(err) {
    if (err) {
      throw err;
    }
    console.log('Loopback tables [' + lbTables + '] created in'
    , mysqlDB.adapter.name);
    mysqlDB.disconnect();
  });
};
```

Now when I run the above script with my attached datasource as `mysqlDS1` the autoupdate function works. However, if I change my the attached datasource and point it to `mysqlDS2` it fails.

```bash
sakibs-mac:test-app ssh$ node .
/Users/ssh/workspace/apic loopback/slc/2017/may17/test-app/server/boot/script.js:10
      throw err;
      ^

Error: Cannot migrate models not attached to this datasource: User ACL RoleMapping Role
    at /Users/ssh/workspace/apic loopback/slc/2017/may17/test-app/node_modules/loopback-datasource-juggler/lib/datasource.js:973:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

**Why does it fail?** Simply because these models `['User', 'ACL', 'RoleMapping', 'Role']` are attached to `mysqlDS1` in the `model-config.json` file. Here is the snippet of that file:
```json
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "User": {
    "dataSource": "mysqlDS1"
  },
  "AccessToken": {
    "dataSource": "mysqlDS1",
    "public": false
  },
  "ACL": {
    "dataSource": "mysqlDS1",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "mysqlDS1",
    "public": false,
    "options": {
      "strictObjectIDCoercion": true
    }
  },
  "Role": {
    "dataSource": "mysqlDS1",
    "public": false
  },
  "Note": {
    "dataSource": "db"
  }
}
```

You can have _**at most one**_ datasource connected to your model at a given time. Hence, if you wanted to autoupdate those models to `mysqlDS2` you had to manually go in `model-config.json` file to fix it.

Please let me know if this solved your problem. :)

**Comment by Mayeu** [comment] 2017-05-02 08:30
Thank you for your response, I am going to take a look at that today.

**Comment by Mayeu** [comment] 2017-05-02 15:19
I appreciate your response, and I am wondering about this point:

>  I was not successful on reproducing your issue.

Were you unable to reproduce the issue with my provided example repository, or did you create a new project from scratch ? (You can find the repository at [Mayeul/oopback-two-mysql-datasource-not-working](/https://github.com/Mayeu/loopback-two-mysql-datasource-not-working)) Because this repository provide the exact version and setup that currently create the issue.

I tried your script (using it in the same minimal repo I previously quoted, and in our actual project), but the result is the same, the migration hang forever and never finish.

Could you provide a full copy of your working example, which version of LoopBack you are using, and on which OS?

I may not have been clear enough in my description, but when I add a new datasource I don't add it to the migration script, nor do I expect to run migration on it. And there is no error nor exception, the script just hang and never finish. Feel free to warn me if I am missing some critical data in my description, or if some point is unclear :)

Thank you for your help.

**Comment by ssh24** [comment] 2017-05-04 16:56
@Mayeu Looks like your script is doing something wrong. This [commit](https://github.com/Mayeu/loopback-two-mysql-datasource-not-working/commit/f221371ef8058aa61b4ed14240122e0e07a30029#diff-cf1e8c14e54505f60aa10ceb8d5d8ab3) only adds the datasource to the `datasources.json`, however the `modelconfig.json` file has all models pointing to `dbone` which is not what you want.
```json
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "User": {
    "dataSource": "dbone"
  },
  "AccessToken": {
    "dataSource": "dbone",
    "public": false
  },
  "ACL": {
    "dataSource": "dbone",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "dbone",
    "public": false,
    "options": {
      "strictObjectIDCoercion": true
    }
  },
  "Role": {
    "dataSource": "dbone",
    "public": false
  }
}
```

**Comment by ssh24** [comment] 2017-05-15 23:37
Closing this as it is not an issue. Feel free to reopen if needed.

**Closed by ssh24** 2017-05-15 23:37 UTC
Labels: apex, triaging

**Comment by Mayeu** [comment] 2017-05-18 13:36
> @Mayeu Looks like your script is doing something wrong. This commit only adds the datasource to the datasources.json, however the modelconfig.json file has all models pointing to dbone which is not what you want.

I am sorry but this is not the issue.

The second database (`dbtwo`) won't be part of the migration, it will only be used to read data from a database not controlled by LoopBack. Thus, it won't be part of the migration.

Adding a model using the DB still lead to the migration script to hang:

```
$ cat server/model-config.json
  [...snip...]
  "Role": {
    "dataSource": "dbone",
    "public": false
  },
  "OtherModel":
  {
    "dataSource": "dbtwo"
  }
}
$ cat common/models/othermodel.json
{
  "name": "OtherModel",
  "base": "Model",
  "idInjection": true,
  "options": {
    "idInjection": true,
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
# running the migration
$  node server/initialiseDatabase.js
Loopback tables [User,ACL,RoleMapping,Role] created in  mysql
# hang indefinitively here
```

The fact that this is not in the demo repository is because the demo repository present the commit from which things stop working. Adding a data source, even without linking it to a model, should not silently break loopback functionality.

> Closing this as it is not an issue. Feel free to reopen if needed.

I don't seem to have the right to reopen the issue.
