### ISSUE TITLE
autoupdate() ALTER TABLE ignores mysql columnName property in model definition.

### ISSUE THREAD

**Issue by codyolsen** [strongloop/loopback-connector-mysql#168] opened 2016-05-24 19:43 UTC
Upon an autoupdate call for a new model with the following properties, the new model table with columns `first_name` and `last_name` are created in the database.

``` javascript
"firstName": {
  "type": "String",
  "required": false,
  "length": 255,
  "precision": null,
  "scale": null,
  "mysql": {
    "columnName": "first_name",
    "dataType": "varchar",
    "dataLength": 255,
    "dataPrecision": null,
    "dataScale": null,
    "nullable": "Y"
  }
},
"lastName": {
  "type": "String",
  "required": false,
  "length": 255,
  "precision": null,
  "scale": null,
  "mysql": {
    "columnName": "last_name",
    "dataType": "varchar",
    "dataLength": 255,
    "dataPrecision": null,
    "dataScale": null,
    "nullable": "Y"
  }
}
```

An additional field is then added to the model definition:

``` javascript
"firstName": {
  "type": "String",
  "required": false,
  "length": 255,
  "precision": null,
  "scale": null,
  "mysql": {
    "columnName": "first_name",
    "dataType": "varchar",
    "dataLength": 255,
    "dataPrecision": null,
    "dataScale": null,
    "nullable": "Y"
  }
},
"lastName": {
  "type": "String",
  "required": false,
  "length": 255,
  "precision": null,
  "scale": null,
  "mysql": {
    "columnName": "last_name",
    "dataType": "varchar",
    "dataLength": 255,
    "dataPrecision": null,
    "dataScale": null,
    "nullable": "Y"
  }
},
"streetAddress": {
  "type": "String",
  "required": false,
  "length": 255,
  "precision": null,
  "scale": null,
  "mysql": {
    "columnName": "street_address",
    "dataType": "varchar",
    "dataLength": 255,
    "dataPrecision": null,
    "dataScale": null,
    "nullable": "Y"
  }
}
```

When calling autoupdate, instead of the new column being added to the table with the mysql:columnName of `street_address`, the new column and all other columns in the model table revert to camel case as `lastName`, `firstName`, `streetAddress`.

I've found that this also happens when a property is removed from a model and autoupdate is called.

**Comment by hasanlussa** [comment] 2016-12-02 09:28
i still experiencing this problems
`"loopback-connector-mysql": "^2.4.0"`

``` bash
...
Error: ER_BAD_FIELD_ERROR: Unknown column 'top' in 'supplier'
...
```
i lookup the problem, and it caused by the method [`mysql.client.escapeId(<property name>)`](https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/migration.js#L310) always returning `propertyName` not the `columnName` before migration routine alter the table.

**Comment by hasanlussa** [comment] 2016-12-03 10:40
ok, the problem is beacause the PR #190  not implemented `columnName` discovery process on add and actualize function.

so i end up forked this repo & create some patch around it
``` js
...
      if (found) {
        actualize(colName, found);
      } else {
        sql.push('ADD COLUMN ' + self.client.escapeId(colName) + ' ' +
...
```

i need to make some tests routine, and will make this little PR soon.

**Comment by jannyHou** [comment] 2016-12-06 21:04
Current behaviour:
When I autoupdate with the model provided in first comment :
```
"streetAddress": {
  "type": "String",
  "required": false,
  "length": 255,
  "precision": null,
  "scale": null,
  "mysql": {
    "columnName": "street_address",
    "dataType": "varchar",
    "dataLength": 255,
    "dataPrecision": null,
    "dataScale": null,
    "nullable": "Y"
  }
```
If column already exists as `street_address`, the name won't change.
But if column doesn't exist, it will be stored as `streetAddress`.


@hasanlussa Can you describe more about your use case? And do you mind creating a pr in this repo to fix it? Thanks. We can help review it.

**Comment by hasanlussa** [comment] 2016-12-07 03:03
``` json
   ...
   "maxDiscount": {
      "type": "number",
      "dataType": "decimal",
      "precision": 5,
      "scale": 2,
      "mysql": {
        "columnName": "PART_DISC_MAX",
        "dataType": "DECIMAL",
        "dataPrecision": 5,
        "dataScale": 2
      }
    }
```
In my case the problem happen if i made change at column's `dataType` or some detail of `dataType`, like `precision` or `length` of the column. If the column doesn't exist, the problem also happen. 

but apparently there is a problem if the index of table is being changed too. I need to make some adjustment with this. I know this `index` feature is still premature, but this feature crucial to my current works.

``` json
    "code": {
      "type": "string",
      "required": true,
      "length": 10,
      "index": {
        "unique": true
      },
      "mysql": {
        "columnName": "PART_NO",
        "dataType": "VARCHAR",
        "dataLength": 10
      }
    },
```

**Comment by rlloyd2001** [comment] 2016-12-07 03:12
I'm pretty sure that auto-update will not do indexing correctly when using a column with the "mysql" rename. It's something that needs to be fixed in loopback last time I checked.

**Comment by jannyHou** [comment] 2016-12-07 22:01
Confirmed.
Besides the situation I described in https://github.com/strongloop/loopback-connector-mysql/issues/168#issuecomment-265271684, `autoupdate` also don't update column like `dataType` accordingly after I updated it in `model.json`.

**Comment by jannyHou** [comment] 2016-12-07 22:06
Closing this issue since the bug described in first comment is already fixed.
And opened new issues to track new bugs:
https://github.com/strongloop/loopback-connector-mysql/issues/222 : `autoupdate` don't update column like `dataType` accordingly after changing it in model.json.

**Closed** 2016-12-07 22:16 UTC
